require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  # Keep a real store: ActionController::RateLimiting counts sign-in attempts in
  # Rails.cache, and with :null_store every increment returns nil, which silently turns
  # the rate limit in SessionsController off. See test/controllers/sign_in_rate_limit_test.rb.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Action Cable's forgery protection stays on. Rails' development default allows
  # http(s)://localhost:<port> plus anything whose Origin equals the host it was sent to
  # (config.action_cable.allow_same_origin_as_host, true by default), so a browser at
  # http://127.0.0.1:3000 already works. These two patterns add the mixed cases, where a page
  # loaded from one spelling of the loopback address opens a socket to the other, so a reviewer
  # who reaches the application by IP literal never loses the live board. Production keeps the
  # strict default: only the origins it is configured for.
  config.action_cable.allowed_request_origins = [
    %r{\Ahttps?://localhost(:\d+)?\z},
    %r{\Ahttps?://127\.0\.0\.1(:\d+)?\z}
  ]

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
